### PR TITLE
Move base example to implementations/base. Add base/test.

### PR DESCRIPTION
**Pull request by ericelliott**

### CODE REVIEW

**Comment by Flet** [comment]
So `implementations/base` will be the template folks will copy?

**Comment by ericelliott** [comment]
Yes.

This will fix https://github.com/ericelliott/todotasks/issues/4

**Comment by ericelliott** [comment]
If this looks good, feel free to smash the Merge button. I'll use the PR process just like everybody else. =)

@jesstelford you should feel free to smash the merge button too if you can beat @Flet to it. =)

**Comment by ericelliott** [comment]
Or @pyramation -- the race is on! =)

**Comment by ericelliott** [comment]
Oops. Forgot to update the README. =)

**Pull request merged**
